### ISSUE TITLE
[golang/hello-world] Panic during sending a message

### ISSUE THREAD

**Issue by Sebor** [mattermost/mattermost-app-examples#14]
I'm following the [guide](https://developers.mattermost.com/integrate/apps/quickstart/quick-start-go/),
but when I try to send any message I get the error in UI `upstream call failed: failed to invoke via HTTP: Post "http://mattermost-apps-golang-hello-world:4000/send": EOF`
and panic in logs:
```
hello-world-mattermost-apps-golang-hello-world-1  | http: panic serving 172.18.0.3:58954: runtime error: invalid memory address or nil pointer dereference
hello-world-mattermost-apps-golang-hello-world-1  | goroutine 6 [running]:
hello-world-mattermost-apps-golang-hello-world-1  | net/http.(*conn).serve.func1()
hello-world-mattermost-apps-golang-hello-world-1  | 	/usr/local/go/src/net/http/server.go:1854 +0xbf
hello-world-mattermost-apps-golang-hello-world-1  | panic({0x1075b40, 0x1ce9170})
hello-world-mattermost-apps-golang-hello-world-1  | 	/usr/local/go/src/runtime/panic.go:890 +0x263
hello-world-mattermost-apps-golang-hello-world-1  | main.Send({0x152a7b0, 0xc0001f8460}, 0xc00016e000)
hello-world-mattermost-apps-golang-hello-world-1  | 	/app/hello.go:149 +0x307
hello-world-mattermost-apps-golang-hello-world-1  | net/http.HandlerFunc.ServeHTTP(0xc0001f8460?, {0x152a7b0?, 0xc0001f8460?}, 0x11ed0a3?)
hello-world-mattermost-apps-golang-hello-world-1  | 	/usr/local/go/src/net/http/server.go:2122 +0x2f
hello-world-mattermost-apps-golang-hello-world-1  | net/http.(*ServeMux).ServeHTTP(0x0?, {0x152a7b0, 0xc0001f8460}, 0xc00016e000)
hello-world-mattermost-apps-golang-hello-world-1  | 	/usr/local/go/src/net/http/server.go:2500 +0x149
hello-world-mattermost-apps-golang-hello-world-1  | net/http.serverHandler.ServeHTTP({0x15283e8?}, {0x152a7b0, 0xc0001f8460}, 0xc00016e000)
hello-world-mattermost-apps-golang-hello-world-1  | 	/usr/local/go/src/net/http/server.go:2936 +0x316
hello-world-mattermost-apps-golang-hello-world-1  | net/http.(*conn).serve(0xc0006f4000, {0x152b290, 0xc00058e2a0})
hello-world-mattermost-apps-golang-hello-world-1  | 	/usr/local/go/src/net/http/server.go:1995 +0x612
hello-world-mattermost-apps-golang-hello-world-1  | created by net/http.(*Server).Serve
hello-world-mattermost-apps-golang-hello-world-1  | 	/usr/local/go/src/net/http/server.go:3089 +0x5ed
```

**Comment by hanzei** [comment]
Thanks for the report @Sebor :+1:

Can you confirm that you are running `master`?

**Comment by Sebor** [comment]
Hi @hanzei!
Yes, I use master branch

**Comment by hanzei** [comment]
Found the issue and submitted a fix

**Comment by Sebor** [comment]
> Found the issue and submitted a fix

Thanks. But I get the same panic with your [changes](https://github.com/mattermost/mattermost-app-examples/pull/15). I tried to debug but I don't have experience in golang.
Suspicion that the problem is in the context. Because there is very little data inside:
```
Client struct is: call: /send, expand: acting_user_access_token:all, context: acting_user_access_token: ***hsjc, bot_access_token: ***dpwe, bot_user_id: m3z9xhtwdtfq8mkfg7r5kmfy1a, values: Message
Context struct is: acting_user_access_token: ***hsjc, bot_access_token: ***dpwe, bot_user_id: m3z9xhtwdtfq8mkfg7r5kmfy1a
Message is: Hello, world! ...and sdfsfsf!
http: panic serving 172.18.0.3:40242: runtime error: invalid memory address or nil pointer dereference
...
```
I've got these logs using the log package:
```
	log.Printf("Client struct is: %v", c)
	log.Printf("Context struct is: %v", c.Context)

	message := "Hello, world!"
	v, ok := c.Values["Message"]
	if ok && v != nil {
		message += fmt.Sprintf(" ...and %s!", v)
		log.Printf("Message is: %s", message)
	}
```

If I comment lines [142](https://github.com/mattermost/mattermost-app-examples/blob/master/golang/hello-world/hello.go#L142) and [144](https://github.com/mattermost/mattermost-app-examples/blob/master/golang/hello-world/hello.go#L144), then there is no panic

**Comment by Sebor** [comment]
@hanzei ah never mind. It's suddenly worked :)
Probably it was docker cache or something similar. Thank you for the fix
